## 基本操作

### 数组创建

In [1]:
import numpy as np # Shift + Enter

In [2]:
# 创建可以将Python，中list列表转换成NumPy数组
l = [1,2,3,4,5]

# NumPy数组
nd1 = np.array(l) # 输入一部分arr + tab（命令中自动补全，按键） 代码提示，自动补全
print(nd1)
display(nd1) # 显示

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

In [3]:
nd2 = np.zeros(shape = (3,4),dtype = np.int16) # shift + tab提示方法的属性，使用
nd2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [4]:
nd3 = np.ones(shape = (3,5),dtype=np.float32)
nd3 # juppyter中执行程序，代码，最后一行，默认就是输出

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [5]:
# 三维数组
nd4 = np.full(shape = (3,4,5),fill_value=3.1415926) # 生成任意指定的数组
nd4

array([[[3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926]],

       [[3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926]],

       [[3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926],
        [3.1415926, 3.1415926, 3.1415926, 3.1415926, 3.1415926]]])

In [7]:
nd5 = np.random.randint(0,100,size = 20) # 从0，到100，生成随机数字，int，整数
nd5

array([88, 68, 55, 25, 95, 45, 53, 52, 94, 48, 38, 41, 12, 66, 18, 38, 15,
       53, 15, 86])

In [8]:
nd6 = np.random.rand(3,5) # 生成0~1之间随机数
nd6

array([[0.1805577 , 0.97917756, 0.09591097, 0.07785931, 0.48850737],
       [0.89135262, 0.37393773, 0.30382903, 0.75894887, 0.27816675],
       [0.75702185, 0.22346079, 0.68415817, 0.40806391, 0.01608321]])

In [9]:
nd7 = np.random.randn(3,5) # 正态分布，平均值是0，标准差是1
display(nd7)

array([[ 0.45444319,  0.91608409, -0.32166309, -1.03094546, -0.46488153],
       [-1.31852167,  0.13591764,  0.7220875 ,  1.40014984,  0.18295841],
       [-0.22589557, -0.94451934,  1.25952318, -1.72418753,  0.65093392]])

In [10]:
nd8 = np.random.normal(loc = 175,scale = 10,size = (3,5)) # 正态分布，平均值是175，标准差是10
print(nd8)

[[158.01782738 178.97018664 180.98631405 172.14661692 175.47228488]
 [174.02104608 182.14529853 146.28615046 183.56698055 173.92432236]
 [185.93646469 180.11427498 188.36019552 183.88039966 182.85760538]]


In [13]:
nd9 = np.arange(1,100,step = 10) # 等差数列，左闭右开，100取不到
nd9

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [19]:
nd10 = np.linspace(1,100,num = 19) # 等差数列，左闭右闭,num表示生成等差数列长度
nd10

array([  1. ,   6.5,  12. ,  17.5,  23. ,  28.5,  34. ,  39.5,  45. ,
        50.5,  56. ,  61.5,  67. ,  72.5,  78. ,  83.5,  89. ,  94.5,
       100. ])

### 查看数组属性

In [1]:
import numpy as np

nd = np.random.randn(5,3)
nd

array([[ 0.12642702,  0.74807666,  2.42032545],
       [-0.27449595, -0.68078987,  0.27759778],
       [ 1.15223642, -0.63332573,  0.28521052],
       [ 0.39521598,  0.6202027 ,  0.90567908],
       [ 0.31221798, -0.19330004, -0.42587603]])

In [2]:
# 查看数组形状，返回了形状 shape = (5,3)
nd.shape

(5, 3)

In [3]:
nd.dtype # 告诉数组的数据类型 float64 位，一位占一个0或者一个1

dtype('float64')

In [4]:
nd.size # 尺寸，数组可以是多维的，请问，里面共有多少数据 3*5 = 15

15

In [5]:
nd.ndim # 数组维度 

2

In [6]:
nd.itemsize # 条目 尺寸长度 8 字节
# 数据类型是float64 64位 -----> 1个字节8位-----> 64/8 = 8 字节

8

### 文件读写

In [8]:
nd1 = np.random.randint(0,100,size = (3,5))
nd2 = np.random.randn(3,5)
display(nd1,nd2)

array([[22, 32, 86, 19, 24],
       [58, 80,  2, 38, 96],
       [82, 47, 28, 32, 96]])

array([[-0.04839046,  0.20762731,  1.70801699, -0.41054106,  1.33676572],
       [-1.25124635,  0.59099474, -0.74312281,  1.09247369, -0.29597477],
       [ 0.90854543,  0.96096231, -1.20553854,  0.9696578 , -0.12783873]])

In [9]:
np.save('./data',nd1) # 把一个数据存到文件中

In [10]:
np.load('./data.npy') # 默认添加npy后缀

array([[22, 32, 86, 19, 24],
       [58, 80,  2, 38, 96],
       [82, 47, 28, 32, 96]])

In [11]:
# 多个数据存到一个文件中
np.savez('./data.npz',a = nd1,abc = nd2) # 保存数据是起名：a,abc,称为key，自己命名

In [12]:
data = np.load('./data.npz')
data

In [13]:
data['a'] # 单引号

array([[22, 32, 86, 19, 24],
       [58, 80,  2, 38, 96],
       [82, 47, 28, 32, 96]])

In [14]:
data['abc']

array([[-0.04839046,  0.20762731,  1.70801699, -0.41054106,  1.33676572],
       [-1.25124635,  0.59099474, -0.74312281,  1.09247369, -0.29597477],
       [ 0.90854543,  0.96096231, -1.20553854,  0.9696578 , -0.12783873]])

In [15]:
data['www'] # 没有保存，无法获取

KeyError: 'www is not a file in the archive'

In [16]:
np.savez_compressed('./data2.npz',x = nd1,y = nd2)

In [17]:
np.load('./data2.npz')['x']

array([[22, 32, 86, 19, 24],
       [58, 80,  2, 38, 96],
       [82, 47, 28, 32, 96]])

In [19]:
np.savetxt(fname = './data.txt',# 文件名
           X = nd1, # 数据
           fmt='%0.2f', # 格式
           delimiter=',')# 分隔符

In [20]:
np.savetxt(fname = './data.cvs',# 文件名
           X = nd1, # 数据
           fmt='%d', # 格式
           delimiter=';')# 分隔符

In [21]:
np.loadtxt('./data.cvs',delimiter=';')

array([[22., 32., 86., 19., 24.],
       [58., 80.,  2., 38., 96.],
       [82., 47., 28., 32., 96.]])

In [23]:
np.loadtxt('./data.txt',delimiter=',')

array([[22., 32., 86., 19., 24.],
       [58., 80.,  2., 38., 96.],
       [82., 47., 28., 32., 96.]])

## 数据类型

In [24]:
# int8，int16，int32，int64，uint8无符号
# float16，float32，float64
# str字符串类型
# int8 表示 2**8个数字 256个 -128 ~ 127 有符号
# uint8 表示256个数字，无符号，表明只有正数：0 ~ 255

np.array([2,4,7],dtype = np.int8)

array([2, 4, 7], dtype=int8)

In [25]:
np.array([-3,-7,255,108,0,256],dtype = np.uint8)

array([253, 249, 255, 108,   0,   0], dtype=uint8)

In [27]:
np.random.randint(0,100,size = 10,dtype = 'int64')

array([59,  9, 31, 47, 90, 84, 89, 10, 85, 13])

In [28]:
nd = np.random.rand(10,2)
nd

array([[0.08697582, 0.01856716],
       [0.28368212, 0.01316251],
       [0.20035117, 0.6809994 ],
       [0.31315228, 0.40969755],
       [0.79286082, 0.24707183],
       [0.60774558, 0.32297674],
       [0.54115188, 0.89123677],
       [0.99941816, 0.15384657],
       [0.52934283, 0.61635984],
       [0.34174069, 0.30613281]])

In [29]:
nd.dtype

dtype('float64')

In [31]:
np.asarray(nd,dtype = 'float16')

array([[0.087  , 0.01857],
       [0.2837 , 0.01316],
       [0.2003 , 0.681  ],
       [0.3132 , 0.4097 ],
       [0.793  , 0.2471 ],
       [0.608  , 0.323  ],
       [0.541  , 0.891  ],
       [0.9995 , 0.1538 ],
       [0.5293 , 0.616  ],
       [0.3418 , 0.3062 ]], dtype=float16)

In [33]:
nd.astype(dtype = np.float16)

array([[0.087  , 0.01857],
       [0.2837 , 0.01316],
       [0.2003 , 0.681  ],
       [0.3132 , 0.4097 ],
       [0.793  , 0.2471 ],
       [0.608  , 0.323  ],
       [0.541  , 0.891  ],
       [0.9995 , 0.1538 ],
       [0.5293 , 0.616  ],
       [0.3418 , 0.3062 ]], dtype=float16)

In [34]:
nd = np.random.randn(1000,3) # 默认数据类型是float64
np.save('./data1',nd)

In [35]:
np.save('./data2',nd.astype('float16'))

In [36]:
nd2 = np.array(list('abcdefghi'))
nd2

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [37]:
nd2.dtype

dtype('<U1')

## 数组运算

### 基本运算

In [38]:
# 加减乘除指数幂运算
nd1 = np.random.randint(0,10,size = 5)
nd2 = np.random.randint(0,10,size = 5)
display(nd1,nd2)

array([8, 8, 6, 8, 9])

array([4, 4, 9, 5, 7])

In [70]:
nd3 = nd1 - nd2 # 返回一个新对象，原来的数组，内容不变！
nd3 # nd3数组操作后，接收的对象

array([-380, -380, -391, -381, -380])

In [41]:
nd1 * nd2 # 乘法

array([32, 32, 54, 40, 63])

In [42]:
nd1 / nd2 # 除法

array([2.        , 2.        , 0.66666667, 1.6       , 1.28571429])

In [43]:
nd1**nd2 # 幂运算

array([    4096,     4096, 10077696,    32768,  4782969])

In [45]:
2**3

8

In [49]:
np.power(2,3) # 表示2的3次幂

8

In [50]:
np.power(nd1,nd2) # 表示nd1的nd2次幂，对应位置，进行计算

array([    4096,     4096, 10077696,    32768,  4782969])

In [46]:
np.log(100) # 底数是自然底数e 2.718

4.605170185988092

In [47]:
np.log10(1000) # 对数运算返回结果是：3

3.0

In [48]:
np.log2(1024) # 返回结果就是：10

10.0

### 逻辑运算

In [51]:
display(nd1,nd2)

array([8, 8, 6, 8, 9])

array([4, 4, 9, 5, 7])

In [52]:
nd1 > nd2

array([ True,  True, False,  True,  True])

In [53]:
nd1 < nd2

array([False, False,  True, False, False])

In [54]:
nd1 >= nd2 # 表示nd1数组中的数据，是否大于等于nd2中的对应位置的数据，如果大于等于，放回True

array([ True,  True, False,  True,  True])

In [55]:
nd1 == nd2 # 两个等号表示逻辑判断，问，是否相等

array([False, False, False, False, False])

### 数组与标量计算

In [58]:
nd1

array([8, 8, 6, 8, 9])

In [56]:
# 数字3，4，5……都是标量
nd1 + 10 # 所有的位置都加了10，广播

array([18, 18, 16, 18, 19])

In [57]:
nd1 - 1024

array([-1016, -1016, -1018, -1016, -1015])

In [59]:
nd1 * 256

array([2048, 2048, 1536, 2048, 2304])

In [60]:
nd1 / 1024

array([0.0078125 , 0.0078125 , 0.00585938, 0.0078125 , 0.00878906])

In [61]:
# 数组可以做分母，注意不能有0
1/nd1

array([0.125     , 0.125     , 0.16666667, 0.125     , 0.11111111])

In [63]:
1/np.array([1,3,0,5]) # 0不能作为分母计算结果：inf 

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([1.        , 0.33333333,        inf, 0.2       ])

### -= += *=直接改变原数组

In [64]:
display(nd1,nd2) # 没变化

array([8, 8, 6, 8, 9])

array([4, 4, 9, 5, 7])

In [65]:
nd1 -= 100 # 没有打印输出，说明，改变了原来的数组

In [66]:
nd1

array([-92, -92, -94, -92, -91])

In [67]:
nd2 +=100
nd2

array([104, 104, 109, 105, 107])

In [68]:
nd1 *= 3
nd1

array([-276, -276, -282, -276, -273])

In [69]:
# nd1 /= 10 数组不支持 /=

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

## 复制和视图

### 完全没有复制

In [71]:
a = np.random.randint(0,10,size = 5)
b = a # 赋值操作
display(a,b)

array([3, 9, 5, 3, 8])

array([3, 9, 5, 3, 8])

In [72]:
a is b # 返回True说明，赋值操作，a和b一回事

True

In [73]:
a[0] = 1024 # 改变a那么b也发生了变化
display(a,b)

array([1024,    9,    5,    3,    8])

array([1024,    9,    5,    3,    8])

### 视图、查看或者浅拷贝

In [75]:
a = np.random.randint(0,100,size = 5)
b = a.view() # 视图，查看，浅拷贝
display(a,b)

array([ 0, 86, 29, 73, 38])

array([ 0, 86, 29, 73, 38])

In [76]:
a is b # 说明a和b不一样

False

In [77]:
a.flags.owndata # a数组数据是自己的

True

In [78]:
b.flags.owndata # b是浅拷贝a的数据，也就是b并不拥有自己的数据

False

In [79]:
a[0] = 1024
b[1] = 2048 # 无论修改谁，最终结果两个数组都发生了变化
display(a,b)

array([1024, 2048,   29,   73,   38])

array([1024, 2048,   29,   73,   38])

### 深拷贝

In [80]:
a = np.random.randint(-100,0,size = 10)
b = a.copy() # 深拷贝，此时，a和b没有关系了
display(a,b)

array([-38, -74, -18, -30,  -1, -81,  -5, -42, -44, -12])

array([-38, -74, -18, -30,  -1, -81,  -5, -42, -44, -12])

In [81]:
display(a is b)
display(a.flags.owndata)
display(b.flags.owndata) # b 对象拥有自己的数据

False

True

True

In [82]:
a[0] = 1024
b[2] = 2048 # 井水不犯河水
display(a,b)

array([1024,  -74,  -18,  -30,   -1,  -81,   -5,  -42,  -44,  -12])

array([ -38,  -74, 2048,  -30,   -1,  -81,   -5,  -42,  -44,  -12])

In [83]:
a = np.arange(1e8) # 0 ~ 1亿，数据量非常多的
a

array([0.0000000e+00, 1.0000000e+00, 2.0000000e+00, ..., 9.9999997e+07,
       9.9999998e+07, 9.9999999e+07])

In [84]:
b = a[[1,3,5,7,9,99]].copy() # 取出一部分数据，原来的数组，没有了，但是占内存特别大
del a # 删除原来的数组，内存优化

In [86]:
b

array([ 1.,  3.,  5.,  7.,  9., 99.])

## 索引、切片和迭代

### 基本索引和切片

In [87]:
a = np.random.randint(0,30,size = 10)
a

array([ 7,  5, 27,  7, 29, 11, 29,  3, 23, 23])

In [90]:
a[3] # 取一个
a[[1,3,5]] # 取多个 

array([ 5,  7, 11])

In [91]:
a[0:3] # 左闭右开

array([ 7,  5, 27])

In [92]:
a[:3] # 如果冒号前面不写，默认从0开始

array([ 7,  5, 27])

In [93]:
a[5:9] # 从某个索引开始切片

array([11, 29,  3, 23])

In [94]:
a[5:] # 冒号后面不写内容，那么默认就是到左后

array([11, 29,  3, 23, 23])

In [95]:
a[::2] # 两个中取一个

array([ 7, 27, 29, 29, 23])

In [96]:
a[3::3] # 从索引3开始，每三个数中，取一个

array([ 7, 29, 23])

In [97]:
a[::-1] # 倒着数，数组进行了颠倒

array([23, 23,  3, 29, 11, 29,  7, 27,  5,  7])

In [99]:
a

array([ 7,  5, 27,  7, 29, 11, 29,  3, 23, 23])

In [98]:
a[::-2] # 颠倒，两个中取一个

array([23,  3, 11,  7,  5])

In [101]:
a[5::-3]

array([11, 27])

In [102]:
a[1:7:2] # 从索引1开始到7结束，每两个中取一个

array([ 5,  7, 11])

In [103]:
b = np.random.randint(0,30,size = (10,10))
b # 二维数组，多维数据索引和切片和上面的规律一样

array([[29, 17,  4, 23,  4, 12, 18, 22,  3,  2],
       [18, 15, 19, 23, 17,  6, 29, 15, 22, 18],
       [10, 20, 16, 11, 18,  3, 10, 20, 16, 28],
       [10,  0,  9, 11,  7, 27, 26, 27, 29, 25],
       [21,  0,  1, 16,  4, 11,  9, 15, 29, 12],
       [15,  3, 29, 26, 17, 15, 22, 23,  8,  3],
       [ 3,  1, 25,  9, 15, 22,  5, 15, 15, 29],
       [ 7,  9, 14, 29, 28,  4,  8, 28,  5, 18],
       [ 0,  2, 19, 10, 18,  0,  9, 16, 10, 19],
       [ 5, 29,  6, 24,  1,  4, 19, 29, 14, 27]])

In [104]:
b[1]

array([18, 15, 19, 23, 17,  6, 29, 15, 22, 18])

In [105]:
b[[0,3,5]]

array([[29, 17,  4, 23,  4, 12, 18, 22,  3,  2],
       [10,  0,  9, 11,  7, 27, 26, 27, 29, 25],
       [15,  3, 29, 26, 17, 15, 22, 23,  8,  3]])

In [107]:
b[1,6]

29

In [108]:
b[3,[2,5,6]] # 多维数组，不怕，我们可以用逗号，分割

array([ 9, 27, 26])

In [110]:
b[2:7,1::3] # 行：从2到索引7。列：从1开始，每3个中取一个数字

array([[20, 18, 20],
       [ 0,  7, 27],
       [ 0,  4, 15],
       [ 3, 17, 23],
       [ 1, 15, 15]])

In [111]:
b[-1,-1] # 给-1表示倒着数

27

In [114]:
b[-2,[-2,-3,-4]]

array([10, 16,  9])

### 花式索引和索引技巧

In [115]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [116]:
b = a[3:7] # 切片时，返回的数据，不是深拷贝
b

array([3, 4, 5, 6])

In [117]:
b[0] = 1024
display(a,b)

array([   0,    1,    2, 1024,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

array([1024,    4,    5,    6])

In [118]:
a = np.arange(20)
# 花式索引返回的深拷贝的数据
b = a[[3,4,5,6]] # 花式索引：就是在索引是，给了一个数组
display(a,b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

array([3, 4, 5, 6])

In [119]:
b[0] = 1024
display(a,b)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

array([1024,    4,    5,    6])

In [120]:
a = np.random.randint(0,151,size = (100,3)) # 100名学生，参加了3门考试:Python、Math、En
a

array([[117, 127, 112],
       [150, 133, 147],
       [104, 114, 123],
       [ 63,  60, 108],
       [111,  18, 121],
       [137,  67,  81],
       [ 14, 125,  38],
       [ 72, 123, 143],
       [132,  13, 114],
       [ 91, 108, 136],
       [ 41,  49,  72],
       [ 79, 148,  20],
       [ 23, 114,  18],
       [146, 144, 125],
       [ 76,  34,  76],
       [134,  45,  91],
       [ 62,  13, 122],
       [ 22,  74,  52],
       [103, 124,  96],
       [ 50, 134, 137],
       [ 82, 126,  23],
       [ 76, 122, 116],
       [116,  11, 115],
       [115,  15,  10],
       [ 12,  31,   4],
       [ 14, 134,  57],
       [ 83, 132,  84],
       [118,  25,  49],
       [109, 123,  63],
       [130, 106, 126],
       [ 25, 145, 103],
       [ 67,  96,  74],
       [ 84,  52,  78],
       [ 54,  79, 137],
       [ 54, 127,  48],
       [ 31,  22,  39],
       [150, 100,  84],
       [122, 123,  14],
       [125,  12,  51],
       [  6,   0,   9],
       [ 25,  18,  42],
       [ 19,  74

In [122]:
cond = a >= 120 # 逻辑运算
# 根据条件，筛选数据，只要大于120，返回，一门大于120，就会返回这一门
a[cond]

array([127, 150, 133, 147, 123, 121, 137, 125, 123, 143, 132, 136, 148,
       146, 144, 125, 134, 122, 124, 134, 137, 126, 122, 134, 132, 123,
       130, 126, 145, 137, 127, 150, 122, 123, 125, 127, 137, 133, 122,
       133, 144, 125, 130, 144, 120, 122, 127, 126, 124, 121, 148, 127,
       142, 139, 136, 121, 140, 135, 130, 125, 135, 140, 136, 131, 138,
       147, 140, 148, 140, 124, 138])

In [127]:
# boolean True = 1;False = 0
# 三门科目的条件进行相乘
# 三个科目都是 大于120的同学
cond2 = cond[:,0]*cond[:,1]*cond[:,2]
a[cond2]

array([[150, 133, 147],
       [146, 144, 125]])

In [129]:
# 大于等于120，小于等于30找到
cond1 = a >=120
cond2 = a <= 30
a[cond2[:,0]*cond2[:,1]*cond2[:,2]]

array([[ 6,  0,  9],
       [ 3, 25, 18]])

## 形状操作

### 数组变形

In [130]:
a = np.random.randint(0,10,size = (3,5))
a

array([[6, 6, 0, 3, 2],
       [5, 8, 8, 3, 6],
       [8, 9, 1, 5, 1]])

In [131]:
a.reshape(5,3) # 只是改变形状

array([[6, 6, 0],
       [3, 2, 5],
       [8, 8, 3],
       [6, 8, 9],
       [1, 5, 1]])

In [134]:
a.reshape(15,1,1)

array([[[6]],

       [[6]],

       [[0]],

       [[3]],

       [[2]],

       [[5]],

       [[8]],

       [[8]],

       [[3]],

       [[6]],

       [[8]],

       [[9]],

       [[1]],

       [[5]],

       [[1]]])

In [135]:
a.reshape(-1,3) # -1表示数据，3自动计算-1 = 5

array([[6, 6, 0],
       [3, 2, 5],
       [8, 8, 3],
       [6, 8, 9],
       [1, 5, 1]])

### 数组转置

In [136]:
# 转置，行变列，列变行
a.T # 矩阵 shape = (5,3)

array([[6, 5, 8],
       [6, 8, 9],
       [0, 8, 1],
       [3, 3, 5],
       [2, 6, 1]])

In [137]:
np.transpose(a,(1,0)) # 行0，列1。默认情况下(0,1)----->调整(1,0)

array([[6, 5, 8],
       [6, 8, 9],
       [0, 8, 1],
       [3, 3, 5],
       [2, 6, 1]])

In [138]:
b = np.random.randint(0,10,size = (3,5,7)) # shape = (0,1,2)
b

array([[[2, 0, 2, 5, 4, 5, 2],
        [6, 9, 2, 9, 2, 0, 7],
        [3, 9, 8, 5, 0, 9, 0],
        [7, 2, 7, 5, 9, 9, 9],
        [0, 2, 6, 8, 4, 8, 3]],

       [[1, 7, 3, 4, 1, 4, 8],
        [6, 4, 7, 5, 9, 7, 4],
        [1, 4, 6, 2, 9, 9, 8],
        [7, 7, 1, 6, 3, 6, 1],
        [7, 5, 0, 4, 7, 2, 1]],

       [[2, 4, 1, 5, 5, 5, 6],
        [6, 8, 7, 5, 4, 2, 2],
        [3, 5, 5, 2, 4, 6, 9],
        [9, 6, 0, 4, 7, 0, 2],
        [5, 7, 8, 6, 5, 6, 0]]])

In [139]:
c = np.transpose(b,(2,1,0)) # 就是调整维度结构2和0维度数据对调
c.shape

(7, 5, 3)

### 数据堆叠合并

In [140]:
nd1 = np.random.randint(0,10,size = (3,5))
nd2 = np.random.randint(0,10,size = (3,5))
display(nd1,nd2)

array([[6, 8, 7, 1, 5],
       [7, 6, 3, 6, 9],
       [1, 5, 4, 5, 7]])

array([[4, 0, 1, 9, 8],
       [6, 1, 9, 7, 7],
       [9, 7, 3, 6, 2]])

In [141]:
np.concatenate([nd1,nd2]) # 默认合并行增加

array([[6, 8, 7, 1, 5],
       [7, 6, 3, 6, 9],
       [1, 5, 4, 5, 7],
       [4, 0, 1, 9, 8],
       [6, 1, 9, 7, 7],
       [9, 7, 3, 6, 2]])

In [142]:
# 修改axis参数调整数据合并方向
np.concatenate([nd1,nd2],axis = 1) # axis 轴，方向 0 = 行，1 = 列

array([[6, 8, 7, 1, 5, 4, 0, 1, 9, 8],
       [7, 6, 3, 6, 9, 6, 1, 9, 7, 7],
       [1, 5, 4, 5, 7, 9, 7, 3, 6, 2]])

In [143]:
np.hstack((nd1,nd2)) # 堆叠，摞起来，增多，合并 h表示水平，列增多

array([[6, 8, 7, 1, 5, 4, 0, 1, 9, 8],
       [7, 6, 3, 6, 9, 6, 1, 9, 7, 7],
       [1, 5, 4, 5, 7, 9, 7, 3, 6, 2]])

In [145]:
np.vstack((nd1,nd2,nd2,nd2,nd1)) # v 竖直，行增加

array([[6, 8, 7, 1, 5],
       [7, 6, 3, 6, 9],
       [1, 5, 4, 5, 7],
       [4, 0, 1, 9, 8],
       [6, 1, 9, 7, 7],
       [9, 7, 3, 6, 2],
       [4, 0, 1, 9, 8],
       [6, 1, 9, 7, 7],
       [9, 7, 3, 6, 2],
       [4, 0, 1, 9, 8],
       [6, 1, 9, 7, 7],
       [9, 7, 3, 6, 2],
       [6, 8, 7, 1, 5],
       [7, 6, 3, 6, 9],
       [1, 5, 4, 5, 7]])

In [156]:
a = np.random.randint(0,10,size = (3,5))
b = np.random.randint(0,10,size = (3,6))
display(a,b)
np.concatenate([a,b])

array([[6, 0, 1, 0, 1],
       [1, 2, 2, 6, 3],
       [3, 0, 1, 8, 1]])

array([[3, 8, 2, 7, 0, 0],
       [0, 1, 4, 6, 2, 3],
       [3, 5, 7, 8, 4, 2]])

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 6

In [157]:
np.concatenate([a,b],axis =1)

array([[6, 0, 1, 0, 1, 3, 8, 2, 7, 0, 0],
       [1, 2, 2, 6, 3, 0, 1, 4, 6, 2, 3],
       [3, 0, 1, 8, 1, 3, 5, 7, 8, 4, 2]])

### 数组拆分

In [146]:
a = np.random.randint(0,100,size = (15,10))
a

array([[27,  2, 90,  2, 27, 37, 81, 85, 43, 44],
       [33, 33, 67, 30, 81, 43, 91,  5, 30, 47],
       [17, 60, 67, 59, 41, 24, 53, 56, 10, 40],
       [64, 20, 49, 76, 17, 25, 27, 18, 67,  9],
       [64, 82,  4, 30, 87, 10, 91, 95, 18, 21],
       [69, 50, 83, 36, 56, 95, 56, 96, 68, 31],
       [97, 40, 64, 50, 64, 51, 25, 32, 19, 99],
       [14, 56, 48, 25, 35, 95, 74, 21, 26, 93],
       [ 0, 70, 17, 81, 54, 69, 41, 39, 22, 97],
       [86, 85, 52, 19, 61, 26, 44, 39, 42, 63],
       [19, 27, 75, 94, 17, 51, 75, 97, 33, 98],
       [46, 70, 37, 59, 34,  4, 98, 31, 37, 19],
       [39, 67, 57, 24, 64, 45, 92,  5, 82, 24],
       [ 1, 46, 89, 24, 85, 70, 97, 87, 37, 62],
       [ 5,  4, 72,  7, 37, 95, 24, 22, 66,  9]])

In [149]:
np.split(a,indices_or_sections=5) # 给数字，表示平均分成多少分

[array([[27,  2, 90,  2, 27, 37, 81, 85, 43, 44],
        [33, 33, 67, 30, 81, 43, 91,  5, 30, 47],
        [17, 60, 67, 59, 41, 24, 53, 56, 10, 40]]),
 array([[64, 20, 49, 76, 17, 25, 27, 18, 67,  9],
        [64, 82,  4, 30, 87, 10, 91, 95, 18, 21],
        [69, 50, 83, 36, 56, 95, 56, 96, 68, 31]]),
 array([[97, 40, 64, 50, 64, 51, 25, 32, 19, 99],
        [14, 56, 48, 25, 35, 95, 74, 21, 26, 93],
        [ 0, 70, 17, 81, 54, 69, 41, 39, 22, 97]]),
 array([[86, 85, 52, 19, 61, 26, 44, 39, 42, 63],
        [19, 27, 75, 94, 17, 51, 75, 97, 33, 98],
        [46, 70, 37, 59, 34,  4, 98, 31, 37, 19]]),
 array([[39, 67, 57, 24, 64, 45, 92,  5, 82, 24],
        [ 1, 46, 89, 24, 85, 70, 97, 87, 37, 62],
        [ 5,  4, 72,  7, 37, 95, 24, 22, 66,  9]])]

In [150]:
np.split(a,indices_or_sections=2,axis =1) # axis = 1 表示列，平均分成两份

[array([[27,  2, 90,  2, 27],
        [33, 33, 67, 30, 81],
        [17, 60, 67, 59, 41],
        [64, 20, 49, 76, 17],
        [64, 82,  4, 30, 87],
        [69, 50, 83, 36, 56],
        [97, 40, 64, 50, 64],
        [14, 56, 48, 25, 35],
        [ 0, 70, 17, 81, 54],
        [86, 85, 52, 19, 61],
        [19, 27, 75, 94, 17],
        [46, 70, 37, 59, 34],
        [39, 67, 57, 24, 64],
        [ 1, 46, 89, 24, 85],
        [ 5,  4, 72,  7, 37]]),
 array([[37, 81, 85, 43, 44],
        [43, 91,  5, 30, 47],
        [24, 53, 56, 10, 40],
        [25, 27, 18, 67,  9],
        [10, 91, 95, 18, 21],
        [95, 56, 96, 68, 31],
        [51, 25, 32, 19, 99],
        [95, 74, 21, 26, 93],
        [69, 41, 39, 22, 97],
        [26, 44, 39, 42, 63],
        [51, 75, 97, 33, 98],
        [ 4, 98, 31, 37, 19],
        [45, 92,  5, 82, 24],
        [70, 97, 87, 37, 62],
        [95, 24, 22, 66,  9]])]

In [151]:
# 参数给列表，根据列表中的索引，进行切片
np.split(a,indices_or_sections=[1,5,9]) # 0~1,1~5,5~9,9~

[array([[27,  2, 90,  2, 27, 37, 81, 85, 43, 44]]),
 array([[33, 33, 67, 30, 81, 43, 91,  5, 30, 47],
        [17, 60, 67, 59, 41, 24, 53, 56, 10, 40],
        [64, 20, 49, 76, 17, 25, 27, 18, 67,  9],
        [64, 82,  4, 30, 87, 10, 91, 95, 18, 21]]),
 array([[69, 50, 83, 36, 56, 95, 56, 96, 68, 31],
        [97, 40, 64, 50, 64, 51, 25, 32, 19, 99],
        [14, 56, 48, 25, 35, 95, 74, 21, 26, 93],
        [ 0, 70, 17, 81, 54, 69, 41, 39, 22, 97]]),
 array([[86, 85, 52, 19, 61, 26, 44, 39, 42, 63],
        [19, 27, 75, 94, 17, 51, 75, 97, 33, 98],
        [46, 70, 37, 59, 34,  4, 98, 31, 37, 19],
        [39, 67, 57, 24, 64, 45, 92,  5, 82, 24],
        [ 1, 46, 89, 24, 85, 70, 97, 87, 37, 62],
        [ 5,  4, 72,  7, 37, 95, 24, 22, 66,  9]])]

In [153]:
np.hsplit(a,indices_or_sections=2) # h水平，列方向上分割成了两份

[array([[27,  2, 90,  2, 27],
        [33, 33, 67, 30, 81],
        [17, 60, 67, 59, 41],
        [64, 20, 49, 76, 17],
        [64, 82,  4, 30, 87],
        [69, 50, 83, 36, 56],
        [97, 40, 64, 50, 64],
        [14, 56, 48, 25, 35],
        [ 0, 70, 17, 81, 54],
        [86, 85, 52, 19, 61],
        [19, 27, 75, 94, 17],
        [46, 70, 37, 59, 34],
        [39, 67, 57, 24, 64],
        [ 1, 46, 89, 24, 85],
        [ 5,  4, 72,  7, 37]]),
 array([[37, 81, 85, 43, 44],
        [43, 91,  5, 30, 47],
        [24, 53, 56, 10, 40],
        [25, 27, 18, 67,  9],
        [10, 91, 95, 18, 21],
        [95, 56, 96, 68, 31],
        [51, 25, 32, 19, 99],
        [95, 74, 21, 26, 93],
        [69, 41, 39, 22, 97],
        [26, 44, 39, 42, 63],
        [51, 75, 97, 33, 98],
        [ 4, 98, 31, 37, 19],
        [45, 92,  5, 82, 24],
        [70, 97, 87, 37, 62],
        [95, 24, 22, 66,  9]])]

In [154]:
np.vsplit(a,indices_or_sections=[3,7,11]) # v表示竖直，行切片，行分割

[array([[27,  2, 90,  2, 27, 37, 81, 85, 43, 44],
        [33, 33, 67, 30, 81, 43, 91,  5, 30, 47],
        [17, 60, 67, 59, 41, 24, 53, 56, 10, 40]]),
 array([[64, 20, 49, 76, 17, 25, 27, 18, 67,  9],
        [64, 82,  4, 30, 87, 10, 91, 95, 18, 21],
        [69, 50, 83, 36, 56, 95, 56, 96, 68, 31],
        [97, 40, 64, 50, 64, 51, 25, 32, 19, 99]]),
 array([[14, 56, 48, 25, 35, 95, 74, 21, 26, 93],
        [ 0, 70, 17, 81, 54, 69, 41, 39, 22, 97],
        [86, 85, 52, 19, 61, 26, 44, 39, 42, 63],
        [19, 27, 75, 94, 17, 51, 75, 97, 33, 98]]),
 array([[46, 70, 37, 59, 34,  4, 98, 31, 37, 19],
        [39, 67, 57, 24, 64, 45, 92,  5, 82, 24],
        [ 1, 46, 89, 24, 85, 70, 97, 87, 37, 62],
        [ 5,  4, 72,  7, 37, 95, 24, 22, 66,  9]])]

## 广播机制

In [161]:
arr1 = np.array([0,1,2,3]*3)
arr1.sort() # 排序，从小到大
arr1 = arr1.reshape(4,3)
arr1

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [162]:
arr2 = np.array([1,2,3])
display(arr1,arr2) # 形状不对应，依然可以进行运算：NumPy底层，为我们进行了广播

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([1, 2, 3])

In [163]:
# 行不够，广播行
arr1 + arr2 # arr2 和arr1 中每一行，进行相加：广播机制 

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [166]:
arr3 = np.array([[1],[2],[3],[4]])
display(arr1,arr3)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

array([[1],
       [2],
       [3],
       [4]])

In [167]:
# 列不够，广播列
arr1 + arr3 # 广播，arr2和arr1中每一列，进行相加：广播

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5],
       [7, 7, 7]])

In [ ]:
# 广播，和复制，意思有点近似

In [168]:
a = np.array([0,1,2,3,4,5,6,7]*3).reshape(3,4,2)
a

array([[[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]]])

In [169]:
b = np.array([0,1,2,3,4,5,6,7]).reshape(4,2)
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [170]:
display(a.shape,b.shape)

(3, 4, 2)

(4, 2)

In [174]:
a * b # b形状(4，2),b 广播了三份

array([[[ 0,  1],
        [ 4,  9],
        [16, 25],
        [36, 49]],

       [[ 0,  1],
        [ 4,  9],
        [16, 25],
        [36, 49]],

       [[ 0,  1],
        [ 4,  9],
        [16, 25],
        [36, 49]]])

## 通用函数

### 元素级数字级别的方法

In [ ]:
# abs、sqrt、square、exp、log、sin、cos、tan，maxinmum、minimum、
# all、any、inner、clip、round、trace、ceil、floor

In [193]:
a = np.array([-1,-3,-5,1,5,8,9])
c = np.random.randint(-5,10,size = 7)
display(a,c)

array([-1, -3, -5,  1,  5,  8,  9])

array([ 7,  2, -2,  6,  7,  7, -3])

In [176]:
np.abs(a) # 求绝对值

array([1, 3, 5, 1, 5, 8, 9])

In [177]:
b = np.array([1,4,9,16,36,49])
b

array([ 1,  4,  9, 16, 36, 49])

In [178]:
np.sqrt(b) # 开平发

array([1., 2., 3., 4., 6., 7.])

In [195]:
np.square(b) # 平方
np.exp(3) # 自然底数e的多少次幂
np.log(20.085536) # 自然底数e对数求解
np.sin(np.pi/2) # 90度sin正弦值
np.cos(0) # 余弦值
np.tan(np.pi/6) # 正切,30度正切值
# 给两个数组，从中选取大的，或者选取小的
np.maximum(a,c) # 从a和c中选取最大的值
np.minimum(a,c) # 选取最小的值

array([-1, -3, -5,  1,  5,  7, -3])

In [197]:
nd1 = np.array([1,3,0]) # 出现0那么对应False，非零True
nd2 = np.array([-1,-3,4,8])
display(nd1,nd2)

array([1, 3, 0])

array([-1, -3,  4,  8])

In [198]:
nd1.any() # 只要有一个True，返回True

True

In [199]:
nd1.all() # 所有True，返回True

False

In [200]:
nd2.all() # 所有的都是True，返回True

True

In [205]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,6])
np.inner(a,b) # 1*1 + 2*2 + 3*3 + 4*4 + 5*6 = 60
# 返回的是两个数组的内积，对应位置相乘加和

60

In [206]:
nd1 = np.random.randint(0,100,size = 30)
nd1

array([17, 33, 69, 70, 81, 58, 47, 79, 60, 16, 34,  1, 72, 23, 27, 64, 73,
       92, 85, 68, 39, 11,  7,  1, 33, 25, 90, 93, 55, 32])

In [207]:
np.clip(nd1,10,80) # 数据裁剪，将小于10变成10，将大于80的变成80

array([17, 33, 69, 70, 80, 58, 47, 79, 60, 16, 34, 10, 72, 23, 27, 64, 73,
       80, 80, 68, 39, 11, 10, 10, 33, 25, 80, 80, 55, 32])

In [208]:
nd2  = np.random.randn(20)
nd2

array([ 0.26615843, -0.02467659,  1.0457321 ,  1.6096884 ,  0.66723395,
       -1.97988073,  0.67701791,  1.68360384, -1.19737442,  1.11051263,
        0.75534365,  0.0654962 , -0.00653493, -0.14014643,  1.00227454,
        1.26102407,  0.13945976, -0.97260932,  1.24669075, -0.35828001])

In [209]:
nd2.round(2)

array([ 0.27, -0.02,  1.05,  1.61,  0.67, -1.98,  0.68,  1.68, -1.2 ,
        1.11,  0.76,  0.07, -0.01, -0.14,  1.  ,  1.26,  0.14, -0.97,
        1.25, -0.36])

In [212]:
np.ceil(np.array([2.7,2.1,2.05])) # 天花板，向上取整

array([3., 3., 3.])

In [213]:
np.floor(np.array([2.99,2.9999,2.1])) # 向下取整

array([2., 2., 2.])

In [220]:
a = np.random.randint(0,10,size = (3,3))
a

array([[9, 7, 6],
       [9, 3, 7],
       [8, 6, 1]])

In [221]:
np.trace(a) # 就算对角线上的和

13

### where函数

In [1]:
import numpy as np
nd1 = np.array([1,3,5,7,9])
nd2 = np.array([2,4,6,8,10])
cond = np.array([True,False,False,True,True])

In [2]:
np.where(cond,nd1,nd2) # 条件如果是True，那么返回nd1中数据，如果Flase返回nd2中数据

array([1, 4, 6, 7, 9])

In [6]:
a = np.random.randint(0,100,size = 50)
display(a) # 数据展示
np.where(a > 50,a,a + 20) # 大于50，返回多少；不然返回-100

array([68,  8, 26, 92, 41,  0, 28, 86,  5, 63, 39, 77, 86,  0, 49, 75, 52,
        3, 25, 91, 93, 42, 99,  6, 90, 90, 73, 70,  7, 20, 56, 17, 42,  0,
       61, 41,  3, 18, 55, 21,  6, 95, 91, 28, 53, 70, 97, 41, 79, 58])

array([68, 28, 46, 92, 61, 20, 48, 86, 25, 63, 59, 77, 86, 20, 69, 75, 52,
       23, 45, 91, 93, 62, 99, 26, 90, 90, 73, 70, 27, 40, 56, 37, 62, 20,
       61, 61, 23, 38, 55, 41, 26, 95, 91, 48, 53, 70, 97, 61, 79, 58])

In [7]:
# 如果分数50~59分之间，自动加10分
a = np.random.randint(0,100,size = 50)
a

array([22, 46, 19, 28, 62, 40,  0,  4,  3, 16, 44, 56, 99, 48, 34, 29, 98,
       38,  9, 58, 56, 98, 49, 23, 61, 33,  8, 95, 52, 54, 28, 27, 83, 44,
       30, 59,  4, 76, 16, 23, 82, 72, 18, 91, 38, 65, 87, 83, 31, 74])

In [10]:
cond = (a >=50) & (a < 60) # 与运算
np.where(cond,a + 10,a)

array([22, 46, 19, 28, 62, 40,  0,  4,  3, 16, 44, 66, 99, 48, 34, 29, 98,
       38,  9, 68, 66, 98, 49, 23, 61, 33,  8, 95, 62, 64, 28, 27, 83, 44,
       30, 69,  4, 76, 16, 23, 82, 72, 18, 91, 38, 65, 87, 83, 31, 74])

### 排序

In [17]:
a = np.random.randint(0,100,size = 20)
a

array([34, 73, 88, 54,  4, 29, 64,  1, 43, 35, 60, 68, 57, 26,  0, 49,  4,
       26, 78, 45])

In [14]:
b = np.sort(a) # 打印输出，那么，原数组，没有改变
b

array([ 1,  5,  5,  9, 10, 20, 22, 38, 47, 52, 57, 66, 76, 77, 78, 90, 93,
       97, 97, 99])

In [15]:
a.sort() # 没有输出，说明，原数组上进行了排序

In [16]:
a

array([ 1,  5,  5,  9, 10, 20, 22, 38, 47, 52, 57, 66, 76, 77, 78, 90, 93,
       97, 97, 99])

In [19]:
index = a.argsort() # 返回排序的索引
display(index)

array([14,  7, 16,  4, 17, 13,  5,  0,  9,  8, 19, 15,  3, 12, 10,  6, 11,
        1, 18,  2])

In [21]:
# 根据索引，花式索引
a[index][::-1]

array([88, 78, 73, 68, 64, 60, 57, 54, 49, 45, 43, 35, 34, 29, 26, 26,  4,
        4,  1,  0])

### 集合操作

In [22]:
a = np.random.randint(0,30,size = 15)
b = np.random.randint(0,30,size = 15)
display(a,b)

array([29,  6, 24, 27, 28, 11, 20, 20, 28, 16, 29, 17,  4, 20, 17])

array([21, 21, 17,  1,  4, 13, 27,  5, 13,  2,  2, 22,  7, 10, 19])

In [23]:
np.intersect1d(a,b) # 交集：a和b中都有

array([ 4, 17, 27])

In [24]:
np.union1d(a,b) # 并集:a和b中的所有，合并

array([ 1,  2,  4,  5,  6,  7, 10, 11, 13, 16, 17, 19, 20, 21, 22, 24, 27,
       28, 29])

In [25]:
np.setdiff1d(a,b) # 差集，a中有，b中没有

array([ 6, 11, 16, 20, 24, 28, 29])

### 数学和统计函数

min、max、mean、median、sum、std、var、cumsum、cumprod、argmin、argmax、argwhere、cov、corrcoef

In [26]:
a = np.random.randint(0,100,size = (3,5))
a

array([[ 7, 17, 76, 21, 55],
       [92, 97, 21, 30, 81],
       [47, 47, 48, 20, 15]])

In [27]:
a.min()

7

In [29]:
a.max(axis = 0) # axis 轴，方向。axis = 0 行，axis = 1列

array([92, 97, 76, 30, 81])

In [30]:
a.max(axis = 1)

array([76, 97, 48])

In [31]:
a.mean() # 平均值

44.93333333333333

In [32]:
np.median(a) # 中位数

47.0

In [33]:
a.sum() # 求和

674

In [34]:
a.std() # 标准差

28.771436452766057

In [35]:
a.var() # 方差，数据内部波动

827.7955555555556

In [36]:
a.cumsum() # 累计和

array([  7,  24, 100, 121, 176, 268, 365, 386, 416, 497, 544, 591, 639,
       659, 674])

In [38]:
b = np.array([1,2,3,4,5,6,7])
b.cumprod() # 累乘和

array([   1,    2,    6,   24,  120,  720, 5040])

In [40]:
a.argmin() # 返回最小值的索引

0

In [41]:
a.argmax() # 返回最大值的索引

6

In [48]:
a

array([[ 7, 17, 76, 21, 55],
       [92, 97, 21, 30, 81],
       [47, 47, 48, 20, 15]])

In [52]:
index = np.argwhere((a > 50) | (a < 20)) # 返回就是符合条件的索引
index

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 4],
       [1, 0],
       [1, 1],
       [1, 4],
       [2, 4]])

In [53]:
for i,j in index:
    print(a[i,j])

7
17
76
55
92
97
81
15


In [54]:
# cov 协方差（属性之间进行计算），方差概念类似（数据内部，属性内部计算）
# 举例子：一个男生受女生欢迎程度，和这名男生萎缩程度，是否成正比，什么关系
np.cov(a)

array([[ 846.2 , -581.3 ,  -52.35],
       [-581.3 , 1291.7 ,   85.65],
       [ -52.35,   85.65,  270.3 ]])

In [55]:
np.corrcoef(a) # 相关性系数，1（正相关） ~ -1（负相关）
# 0 表示，没有线性关系

array([[ 1.        , -0.55601049, -0.10946043],
       [-0.55601049,  1.        ,  0.14495177],
       [-0.10946043,  0.14495177,  1.        ]])

## 线性代数

In [56]:
A = np.random.randint(0,10,size = (3,3))

B = np.random.randint(0,10,size = (3,4))
display(A,B) # A矩阵列长度必须和B行长度一致，不然报错

array([[4, 5, 0],
       [7, 4, 4],
       [9, 0, 9]])

array([[9, 5, 7, 2],
       [5, 3, 5, 0],
       [8, 2, 6, 5]])

In [57]:
A.dot(B) # dot矩阵乘法 ，点乘

array([[ 61,  35,  53,   8],
       [115,  55,  93,  34],
       [153,  63, 117,  63]])

In [58]:
np.dot(A,B) # 模块提供的方法

array([[ 61,  35,  53,   8],
       [115,  55,  93,  34],
       [153,  63, 117,  63]])

In [59]:
A @ B # 邮件中@符号，表示矩阵运算

array([[ 61,  35,  53,   8],
       [115,  55,  93,  34],
       [153,  63, 117,  63]])

In [60]:
C = np.random.randint(0,10,size = (4,5))
C

array([[0, 4, 3, 6, 5],
       [6, 9, 4, 8, 3],
       [5, 9, 8, 1, 2],
       [8, 8, 6, 7, 2]])

In [61]:
A.dot(C) # 形状不对应，无法进行矩阵乘法

ValueError: shapes (3,3) and (4,5) not aligned: 3 (dim 1) != 4 (dim 0)

In [62]:
# B.shape = (3,4);C.shape = (4,5)
B.dot(C)

array([[ 81, 160, 115, 115,  78],
       [ 43,  92,  67,  59,  44],
       [ 82, 144, 110, 105,  68]])

In [63]:
# C.shape = (4,5);B.shape = (3,4)
C.dot(B) # 矩阵乘法不满足交换律！！！

ValueError: shapes (4,5) and (3,4) not aligned: 5 (dim 1) != 3 (dim 0)

## <font color = red>实战</font>-用NumPy分析鸢尾花花萼属性各项指标

案列：读取iris数据集中的花萼长度数据（已保存为csv格式）  
并对其进行排序、去重，并求出和、累积和、均值、标准差、方差、最小值、最大值。

In [64]:
iris = np.loadtxt('./iris.csv') # 花萼长度
iris

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [65]:
iris = np.sort(iris) # 排序操作
iris

array([4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8,
       4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5. , 5. , 5. , 5. ,
       5. , 5. , 5. , 5. , 5. , 5. , 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1,
       5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4,
       5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6,
       5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8,
       5.8, 5.8, 5.9, 5.9, 5.9, 6. , 6. , 6. , 6. , 6. , 6. , 6.1, 6.1,
       6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3,
       6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5,
       6.5, 6.5, 6.5, 6.6, 6.6, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7,
       6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7. , 7.1, 7.2, 7.2, 7.2, 7.3,
       7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9])

In [67]:
# 去除重复数据
iris = np.unique(iris)
iris

array([4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9])

In [68]:
np.sum(iris) # 求和

210.39999999999998

In [69]:
np.mean(iris) # 求平均值

6.011428571428571

In [71]:
np.cumsum(iris) # 累加和

array([  4.3,   8.7,  13.2,  17.8,  22.5,  27.3,  32.2,  37.2,  42.3,
        47.5,  52.8,  58.2,  63.7,  69.3,  75. ,  80.8,  86.7,  92.7,
        98.8, 105. , 111.3, 117.7, 124.2, 130.8, 137.5, 144.3, 151.2,
       158.2, 165.3, 172.5, 179.8, 187.2, 194.8, 202.5, 210.4])

In [72]:
np.median(iris) # 中位数

6.0

In [73]:
np.var(iris) # 方差

1.0587265306122449

In [74]:
np.std(iris) # 标准差

1.0289443768310533

In [75]:
 iris.min() # 最小值

4.3

In [76]:
iris.max() # 最大值

7.9

In [77]:
np.max(iris)

7.9